NO_STORY Resolve policy script failed to compile with nashorn
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
at deployment.bwreg-kit-prod-postgres-2.8.0-SNAPSHOT.ear.bwreg-service.jar//edu.kit.scc.webreg.service.impl.PolicyServiceImpl.resolvePoliciesForService(PolicyServiceImpl.java:118)
Unclear why. On other occasions script compilation works. Bringing this
class in deployment-structure modules makes it work again.